x, y = input("Enter two numbers:\n").split(" ")
print("The inputs are ", x, " and ", y, ", and the sum is: ", int(x) + int(y))
print("The inputs are ", int(x), " and ", int(y), ", and the difference is: ", int(x) - int(y))
print("The inputs are ", int(x), " and ", int(y), ", and the product is: ", int(x) * int(y))
print("The inputs are ", int(x), " and ", int(y), ", and the quotient is: ", int(x) / int(y))
print("The inputs are ", int(x), " and ", int(y), ", and the remainder is: ", int(x) % int(y))
